version: "3"

services:

  backend:
    build:  
      context: ./backend
      dockerfile: Dockerfile
    command: ./run_backend.sh
    volumes:
      - .:/app/
      - /app/backend/node_modules
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    env_file:
      - ./backend/.env

  frontend:
    build:  
      context: ./frontend
      dockerfile: Dockerfile
    command: ./run_frontend.sh
    volumes:
      - .:/app/
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
