version: "3"

services:

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/pgsql/data/video_analytics_technical_test:/var/lib/postgresql/data/

  backend:
    build:  
      context: ./backend
      dockerfile: Dockerfile
    command: ./run_backend.sh
    volumes:
      - .:/app/
      - /app/backend/node_modules
    ports:
      - "8000:8000"
      - "5555:5555"
    environment:
      - PORT=8000
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:  
      context: ./frontend
      dockerfile: Dockerfile
    command: ./run_frontend.sh
    volumes:
      - .:/app/
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
